repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        types: [go]
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'golangci-lint run ./...'
        language: system
        types: [go]
        pass_filenames: false
      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        types: [go]
        pass_filenames: false
      - id: coverage
        name: coverage (100%)
        entry: scripts/coverage.sh
        language: system
        types: [go]
        pass_filenames: false
